# Generated by Django 3.2.8 on 2021-10-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pos_Freq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, null=True)),
                ('freq', models.IntegerField(null=True)),
            ],
        ),
    ]
