# Generated by Django 3.2.8 on 2021-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('star', models.CharField(max_length=2)),
                ('review', models.CharField(max_length=100)),
            ],
        ),
    ]
