# Generated by Django 3.2.8 on 2021-10-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_global_city_global_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='global_state',
            old_name='city',
            new_name='state',
        ),
    ]
